### ISSUE TITLE
failed to open the WinDivert device (5)

### ISSUE THREAD

**Issue by ykpon** [basil00/Divert#302] opened 2022-03-14 10:43 UTC
Hi
I'm trying to run test programs from this release and I'm getting an error
https://github.com/basil00/Divert/releases/tag/v2.2.0
`failed to open the WinDivert device (5)`
Runned as administrator. Before run i'm run
`sc stop windivert`
`sc delete windivert`

Windows 11 21H2 22000.556
Test-signing mode is enabled.

**Comment by basil00** [comment] 2022-03-20 01:53
These kind of mysterious errors tend to be caused by registry entry corruption.  Try manually deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert` registry entry and reboot.

**Comment by ykpon** [comment] 2022-03-21 14:09
I don't have such a registry entry.

**Comment by basil00** [comment] 2022-03-21 22:29
In that case, I am not sure.  I've never seen a (5) error when run as Administrator.

**Comment by basil00** [comment] 2022-04-08 00:45
Usually this is a corrupted registry entry.  If not, then I am not sure, so I cannot help unless more details are provided.  So close this for now.

**Closed by basil00** 2022-04-08 00:45 UTC

**Comment by PinkD** [comment] 2022-12-12 18:23
> These kind of mysterious errors tend to be caused by registry entry corruption. Try manually deleting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert` registry entry and reboot.

That works for me. The original registry points to a directory that does not exist. After deleting and rebooting, the driver works now.
