### ISSUE TITLE
The issue build is not recognised as an internal or external command on my windows command prompt

### ISSUE THREAD

**Issue by raphaeljuwe** [basil00/Divert#93] opened 2017-08-22 15:23 UTC
My  environment is  windows 10, visual studio 2015 with windows driver and SDK install. Had been having this issue  for the past  five hours "build is not recognized as an internal or external command". had even placed  the  "wddk-build.bat" under system environment. 

execution it only create the install directory  

Would really  appreciate an insight from you

**Comment by basil00** [comment] 2017-08-23 02:03
I think this is a duplicate of #88.  The current WinDivert build system specifically requires WDK 7.1.0.

**Closed by basil00** 2017-08-23 02:03 UTC
