### ISSUE TITLE
Reinjected (unmodified) outbound packet is discarded by NIC/Windows when TCP Checksum Offloading is turned on NIC

### ISSUE THREAD

**Issue by geniuss99** [basil00/Divert#134] opened 2018-06-11 07:07 UTC
**Info**: Windows 7 x64, WinDivert 1.4, NIC - Intel 82579V (driver version 12.2.45.0) with TCP checksum offloading turned on.
**Problem**: the "passtru" example doesn't work out of the box.

The _WinDivertSend()_ function reports that packet was successfully reinjected yet the packet does not leave the PC.
Debugging the code I've found the following:
1. _WinDivertRecv()_ extracts packet with ip_checksum == 0 and tcp_checksum equals to some number which is not valid.
2. _WinDivertHelperCalcChecksums()_ doesn't calculate the correct checksum by default.
3. If I disable so called "_PseudoTCPChecksum_" mechanism (see code example) then _WinDivertHelperCalcChecksums()_ calculates tcp checksum correctly and packet does leave the PC.

Why is this happening? Is this the bug in NIC's driver or WinDivert/WFP specific behaviour? Or "_PseudoTCPChecksum_" mechanism in WinDivert code is incorrectly implemented?

Here is the quote from WinDivert's Changelog:
> - The WINDIVERT_HELPER_NO_REPLACE flag for WinDivertHelperCalcChecksums()
>   has been deprecated.  It is no longer necessary to calculate checksums
>   for unmodified packets.

Also I would like to quote you (author) from #43:

> For some reason Windows also requires injected packets to have valid checksums, regardless of the checksum offloading configuration. Therefore you must always call WinDivertHelperCalcChecksums() (or calculate the checksums yourself) before injection via WinDivertSend().

Code snippet:
```
int main()
{
    UINT8 rawPacket[MAX_TCP_PACKET_SIZE];

    WINDIVERT_ADDRESS packetAddress = { 0 };
    UINT packetLengthBytes = 0;

    PWINDIVERT_IPHDR  ipHeader  = { 0 };
    PWINDIVERT_TCPHDR tcpHeader = { 0 };

    const char* filter = "tcp.DstPort == 123";
    HANDLE hWindivertHandle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK, 123, WINDIVERT_FLAG_DEBUG);

    while (true) {
        DWORD dwResult = WinDivertRecv(hWindivertHandle, rawPacket, sizeof(rawPacket), &packetAddress, &packetLengthBytes);
        if (!dwResult) {
            fprintf(stderr, "warning: failed to read packet (%d)\n", dwResult);
            continue;
        }

        BOOL bResult = WinDivertHelperParsePacket(rawPacket, packetLengthBytes, &ipHeader, NULL, NULL, NULL, &tcpHeader, NULL, 0, 0);

        //packetAddress.PseudoTCPChecksum = 0; // resolves the problem
        WinDivertHelperCalcChecksums((PVOID)rawPacket, packetLengthBytes, &packetAddress, 0);

        dwResult = WinDivertSend(hWindivertHandle, rawPacket, packetLengthBytes, &packetAddress, NULL);
        if (!dwResult) {
            fprintf(stderr, "warning: failed to resend packet (%d)\n", GetLastError());
            continue;
        }
    }

    WinDivertClose(hWindivertHandle);
    return 0;
}
```

**Comment by basil00** [comment] 2018-06-11 11:30
Thanks for the report.

> Problem: the "passtru" example doesn't work out of the box.

It should work out-of-the-box which means there is a bug somewhere, whether in WinDivert or elsewhere.  I did a quick test with (Windows 10 virtual machine, TCP checksum offload enabled), and `passthru` worked as expected.

Maybe first thing to check is whether it is inbound or outbound packets that are the problem.  E.g., with filter `tcp.DstPort == 123 and outound` or `tcp.DstPort == 123 and inbound`.

> Also I would like to quote you (author) from #43

That comment is out-of-date, before it was discovered that [pseudo-header checksums](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Checksum_computation) also work.  This was not exactly well-documented, so took a while to figure out.

**Comment by geniuss99** [comment] 2018-06-11 15:34
`passthru `also works for me on Windows 7 x64 VM with TCP checksum offload enabled on default NIC. No problems here.
I suspect the problem might be with my NIC: the way it handles TCP checksum offloading process.

I found this post which might be of interest to you:
http://osronline.com/showthread.cfm?link=280597

I'm not a kernel driver developer but I found this quote interesting:

> You can’t “force” the NIC to do checksum calculation, the NIC can offer to do it 
> with certain constraints, and the TCP stack will ask the NIC to take care of if 
> those constraints are met. Your filter needs to assure it doesn’t change packets 
> such that they violate the agreed-on constraints. **For example, some NICs can do 
> TCP checksum, if there are no option headers, but if there are option headers, 
> the transport will have to do the checksum in software.** If your filter stuffs IP 
> or TCP option headers into the packet, you may then be responsible for the FULL 
> checksum calculation.


Could it be the case?
And if so does this mean that WinDivert driver's "TCP checksum offloading code" (via pseudo-header mechanism) is not compatible with all NICs?
And how does OS Windows handles such scenarios?

More questions than answers :) Do you have any ideas?

**Comment by geniuss99** [comment] 2018-06-12 15:04
> so when you noticed the issue, were you using TCP over IPv6?

No, TCP over IPv4.

> Also, two reports in two days, so the bug may have been triggered by a recent Windows update.

To clarify: I'm seeing this issue on my development PC and only on version 1.4.1 Version 1.2 which I used recently works fine. Also I didn't install any Windows updates recently.

**Comment by kelvinomolumo** [comment] 2018-06-12 20:10
Hello i think this is a bug in WinDivert 1.4. I have the same issue using either version 1.4 and 1.4.1 on both Windows 7 x64 & Windows 10 x64. Initially i thought it was a bug somewhere in my code. But changing the code to always calculate checksum from scratch by leaving out the PWINDIVERT_ADDR portion null solved this issue for me `WinDivertCalcChecksums(packet, packetLength, nullptr, 0);`

**Comment by basil00** [comment] 2018-06-13 14:06
Thanks @kelvinomolumo.  I think there might be a misinterpretation in the way pseudo checksums are handled.  So maybe the current current solution works "some" of the time, but not universally.

Whatever the cause, I committed a change to `WinDivertSend` so that it will calculate the "full" checksums before forwarding the packet to the driver.  This change is compatible with the current WinDivert 1.4 API, and also does not require any modification to the driver.

The only problem with the patch is that it means the packet and address may be "modified" by `WinDivertSend`.  These arguments are non-`const` under the current API, so technically there was not a guarantee that they won't be modified, but still is not an ideal solution.  Actually I can't even remember why they are non-`const`.

**Comment by basil00** [comment] 2018-06-26 01:14
WinDivert 1.4.2 with the work around is now available here: https://github.com/basil00/Divert/releases/tag/v1.4.2

The 1.4 interface is unchanged: captured packets may still have "pseudo" checksums, and the user can still create packets with pseudo checksums.  However, the `WinDivertSend` function will automatically replace any pseudo checksum with full checksums before forwarding the packet to the driver.  It does so "in place", meaning that `WinDivertSend` may modify the `packet` and `addr` buffers, so these should not be `const` memory (the API expects them to be non-`const` anyway).

I may revisit this issue when I have more time.  It is likely that the pseudo checksum implementation is wrong, or was based on a misunderstanding of how pseudo checksums work, or some other issue.

**Closed by basil00** 2018-06-26 01:14 UTC

**Comment by kelvinomolumo** [comment] 2018-07-17 13:56
@basil00 just a quick one...Now that WinDivertSend recalculate the checksum if checksum offloading is enable is it still necessary to use WinDivertCalcChecksums on such packets? Or is it overkill because it will be like we are calling the function twice???

**Comment by basil00** [comment] 2018-07-17 14:39
Under the new behavior, pseudo checksums can be any value, so you will get away with not calling `CalcChecksums`.  This is not "officially" part of the 1.4 WinDivert API, but maybe that should be changed.  Furthermore, perhaps `CalcChecksums` should be a NOP for pseudo checksums.

**Comment by kelvinomolumo** [comment] 2018-07-17 18:58
Exactly what I was thinking @basil00. In lieu of always checking if checksum offloading is enabled, I also think WinDivertCalcChecksums should be a NOP for pseudo checksums. Thanks for your time!

**Comment by ChenYuchenYY** [comment] 2018-10-31 02:47
Problem：the "passtru" example seems not work with the xen net device driver（version:3.0.144.590）.

When the Checksum Offload is Enabled  WinDivertSend() function reports that packet was successfully reinjected yet the packet does not leave the PC. Then disable the Checksum Offload the passthru worked as expected.(The WinDivert what I used is 1.4.3)
